# Vulnerability Type Classification
The following models will be used to see which one performs best when attempting to classify a vulnerability type in a program:
- Decision Tree
- K-Nearest Neighbors
- Naive Bayes

### Setting variables

In [1]:
import os, sys
import numpy as np
import pandas as pd

vType = "ALL"
randomSeed = 1099
numSamples = 500 #Max Num of slice samples from each file
d2vmodelPath = '../d2vModel/model/d2vModel_ALL'
vectorPath =  '../data/vector/'
vectorTrainPath = '../data/DLvectors/train/'
vectorTestPath = '../data/DLvectors/test/'
dlInputsTrainPath = '../data/DLinputs/train/'
dlInputsTestPath  = '../data/DLinputs/test/'

%env VUL_PATH=/Users/crystalcontreras/Desktop/DePaul/VulnerabilitiesResearch/vulnerability_detection

env: VUL_PATH=/Users/crystalcontreras/Desktop/DePaul/VulnerabilitiesResearch/vulnerability_detection

### Updating path
Must insert path to directory above in order to access files in main

In [2]:
VUL_PATH = os.environ.get('VUL_PATH')
sys.path.insert(1, VUL_PATH)

### Import data

In [3]:
from MLMethods import getTrainingData

In [202]:
dataset, labels, sard_cve_ids, testcases, vtypes = getTrainingData(vectorTrainPath, 1, randomSeed)
df = pd.DataFrame({'testcase': testcases, 'sard_cve_id': sard_cve_ids, 'vtype': vtypes, 'label': labels})
df

Getting Balanced Training dataset...
balancedClassTrain.pkl

    testcase sard_cve_id vtype  label
0     298166       98302    AE      1
1     298347       94962    AE      1
2      58812      149093   ARR      1
3        457      102220   PTR      1
4      58719      151618   ARR      0
..       ...         ...   ...    ...
771    58533      150946   ARR      0
772    58761      152959   ARR      0
773       13       92956   PTR      0
774    58472      151098   ARR      0
775    58430      149381   ARR      1

[776 rows x 4 columns]

In [203]:
groups_df = pd.read_csv('../data/CVE/SARD_CVE_to_groups.csv', index_col=0)
groups_df

         Original ID  Group ID
0      CVE-2013-0799       664
1      CVE-2016-2328       664
2      CVE-2012-1184       664
3      CVE-2016-1953       664
4      CVE-2015-0829       664
...              ...       ...
18875           1960       710
18876         105325       664
18877         105312       664
18878           1762       664
18879          98276       691

[18880 rows x 2 columns]

In [224]:
def set_group_id(df, group_df):
    df['group_id'] = None
    for i, row in df.iterrows():
        sard_cve_id = row['sard_cve_id']
        try:
            group_id = group_df.loc[group_df['Original ID'] == sard_cve_id]['Group ID'].item()
            # print(f'group id: {group_id}.  group id type: {type(group_id)}')
            group_id = int(group_id)
            df.at[i, 'group_id'] = int(group_id)
        except:
            print(f'Sample {sard_cve_id} has no group id')

In [214]:
set_group_id(df, groups_df)
df

    testcase sard_cve_id vtype  label group_id
0     298166       98302    AE      1      710
1     298347       94962    AE      1      682
2      58812      149093   ARR      1      707
3        457      102220   PTR      1      664
4      58719      151618   ARR      0      664
..       ...         ...   ...    ...      ...
771    58533      150946   ARR      0      682
772    58761      152959   ARR      0      664
773       13       92956   PTR      0      710
774    58472      151098   ARR      0      697
775    58430      149381   ARR      1      710

[776 rows x 5 columns]

In [237]:
test_df = pd.DataFrame({'a': [1, None, 3, 4], 'b': [2, 3, 4, 6], 'c':[1, None, 3, None]})
print(test_df)
null_indices = pd.isnull(test_df).any(1).to_numpy().nonzero()[0]
null_indices

     a  b    c
0  1.0  2  1.0
1  NaN  3  NaN
2  3.0  4  3.0
3  4.0  6  NaN

array([1, 3])

In [238]:
null_indices = pd.isnull(df).any(1).to_numpy().nonzero()[0]
print('Indices with null values (looking for null group ids in particular)', null_indices)

Indices with null values (looking for null group ids in particular) []

In [221]:
# Drop any rows that are missing group ids
print(df.shape)
df.dropna(inplace=True)
print(df.shape)

(776, 5)
(776, 5)

In [239]:
# Set training data
data = pd.DataFrame(dataset)
data.drop(index=null_indices, inplace=True)
X_train = data.values

In [240]:
# Set target attribute 
target = df['group_id'].values
target = target.astype('int')

## Decision Tree

In [241]:
from sklearn import neighbors, tree, naive_bayes
from sklearn.model_selection import GridSearchCV

In [148]:
model = tree.DecisionTreeClassifier()
sample_leaf_fractions = np.linspace(0.0005, 0.02, 15)*13.06
sample_split_fractions = np.linspace(0.0005, 0.015, 10)*13.06
scoring = 'accuracy'

parameters = {
    'criterion': ['entropy','gini'],
    'max_depth': np.linspace(1, 20, 10),
    'min_samples_leaf': sample_leaf_fractions,
    'min_samples_split': sample_split_fractions
}

In [149]:
def get_grid(model, parameters, scoring, X, Y=None, vb=1):
    grid = GridSearchCV(estimator=model, param_grid=parameters, scoring=scoring, return_train_score=True, verbose=vb)
    grid.fit(X,Y)
    print("Best params: ", grid.best_params_)
    print("Best Score: ", grid.best_score_)
    return pd.DataFrame(grid.cv_results_)

In [245]:
grid_cv_results = get_grid(model, parameters, scoring, X_train, target)

Fitting 5 folds for each of 3000 candidates, totalling 15000 fits

/opt/anaconda3/envs/SySe_VulnerabilityDetection/lib/python3.7/site-packages/sklearn/model_selection/_split.py:668: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)

Best params:  {'criterion': 'entropy', 'max_depth': 11.555555555555555, 'min_samples_leaf': 0.00653, 'min_samples_split': 0.00653}
Best Score:  0.6507940446650124

<font color='red'>TO DO:
- Get test dataset (balanced)
- measure performance
</font>

```
from sklearn import metrics

def measure_performance(X, y, clf, show_accuracy=True, show_classification_report=True, show_confussion_matrix=True):
    y_pred = clf.predict(X)   
    if show_accuracy:
         print ("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")
    
    if show_classification_report:
        print ("Classification report")
        print (metrics.classification_report(y, y_pred),"\n")
      
    if show_confussion_matrix:
        print ("Confusion matrix")
        print (metrics.confusion_matrix(y, y_pred),"\n")
```

## K-Nearest Neighbors

In [253]:
model = neighbors.KNeighborsClassifier()
scoring = 'accuracy'

parameters = {
    'n_neighbors': np.arange(1, 9, 1),
    'weights': ['uniform', 'distance'],
    'p': [1, 2], # 1 = manhattan distance, 2 = euclidean distance
}

In [254]:
grid_cv_results = get_grid(model, parameters, scoring, X_train, target)

Fitting 5 folds for each of 32 candidates, totalling 160 fits

/opt/anaconda3/envs/SySe_VulnerabilityDetection/lib/python3.7/site-packages/sklearn/model_selection/_split.py:668: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)

Best params:  {'n_neighbors': 4, 'p': 2, 'weights': 'distance'}
Best Score:  0.7461290322580645

## Naive Bayes
I don't expect this method to perform well since Bayes' theorem assumes features are strongly independent, when in fact ours is tightly coupled. https://scikit-learn.org/stable/modules/classes.html?highlight=naive%20bayes#module-sklearn.naive_bayes 
#### Gaussian NB

In [246]:
nbclf = naive_bayes.GaussianNB()
nbclf = nbclf.fit(X_train, target)
print ("Score on Training: ", nbclf.score(X_train, target))

Score on Training:  0.30412371134020616

#### Multinomial NB
> The multinomial Naive Bayes classifier is suitable for classification with discrete features (e.g., word counts for text classification).

https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html#sklearn.naive_bayes.MultinomialNB

In [248]:
nbmclf = naive_bayes.MultinomialNB()
nbmclf = nbclf.fit(X_train, target)
print ("Score on Training: ", nbmclf.score(X_train, target))

Score on Training:  0.30412371134020616